Feature#18 withouth the docs folder
unvoid-io/js-client pull request #21
Opened 2022-05-19 20:27 UTC by GeraldWicks

Adresses: [#18](https://github.com/gravwell/js-client/issues/18)

This pr has added an implementation to generate a docs every time we run `npm run start:docs`, then go to `http://localhost:8080`. This will look at all folders inside `./scr` and will generate a docs inside `./docs`.

After this new pr, isn't need to set anything to generate the docs, the docs-generator loops through `./src` and create all the docs by himself.

Although we have so many files changes, don't get mad, the only place that is needed to do a review is inside `docs-generator` folder.

Gonna give a brief explanation what each folder do (inside doc-generator), anyway, I also added a comment in every file, to help to understand.

- assets: this folder has many files that will be copied to the docs folder, all these files are relevant to generate a nice homePage.
- files-manager: this folder helps to copy files, create files, delete files, edit files and also see all files inside a folder.
- folder-manager: this folder will help to create folder and see all subfolders inside a folder.
- home-page: it has the .html file that will be copied to docs folder
- pages: only has the Page interface
- readme: these readmes define a piece of the page that will show up, for example, on the functions page, the readme will represent this red line:
![Captura de tela de 2022-05-19 14-56-39](https://user-images.githubusercontent.com/69917459/169367359-a3284534-cad3-4d5c-b18a-58db147af29c.png)
- scripts: these folder will be responsible to have all the scripts that will be added to the bottom of the .html pages, these scripts are important, because they will change some default behaviors from typedoc lib (the lib used to generate these docs)
- settings: this folder will have some important files as like blackListFolders, paths and licenses.
- typedoc: on this folder that the typedoc lib will create the docs pages.

2022-05-19 20:35 UTC, Puszkarek requested changes

2022-05-19 20:35 UTC, Puszkarek commented on README.md
> +First run `npm install`, to inastall all dependencies, then run `npm run start:docs`, then the docs from this project will be generated and a server on port 8080 will be started, so go to `http://loc
M: fix typo `inastall`

2022-05-19 20:35 UTC, Puszkarek commented on docs-generator/create-docs-pages.ts
> +// it will change the title page, created by default by typedoc
M: use the [TSDoc ](https://tsdoc.org/) notation instead
```
/**
 * 
 */
```

2022-05-19 20:35 UTC, Puszkarek commented on docs-generator/create-docs-pages.ts
> +// it will change the breadCrumb, created by default by typedoc
M: use the [TSDoc ](https://tsdoc.org/) notation instead

2022-05-19 20:35 UTC, Puszkarek commented on docs-generator/files-manager/add-code-block.ts
> +// <script>console.log('hello world')</script>
M: use the [TSDoc ](https://tsdoc.org/) notation instead

2022-05-19 20:35 UTC, Puszkarek commented on docs-generator/files-manager/copy-file.ts
> +	copyFileSync(pathWhereFileIsCopied, pathWhereFileIsPasted);
M: why do we have this method? she is doing the same thing as the `copyFile`

2022-05-19 20:35 UTC, Puszkarek commented on docs-generator/files-manager/create-file.ts
> +// it will create a file inside filePath, with the `data` on injected on this file.
M: use the [TSDoc ](https://tsdoc.org/) notation instead

2022-05-19 20:35 UTC, Puszkarek commented on docs-generator/files-manager/create-file.ts
> +	!existsSync(filePath) && writeFileSync(filePath, data);
S: `&&` is a AND operator, but the method returns void. Is that right? or did you want to call [??](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator)

2022-05-19 20:38 UTC, GeraldWicks commented on docs-generator/files-manager/create-file.ts
> +	!existsSync(filePath) && writeFileSync(filePath, data);
yes, that's right, but if you prefer I can add an if(). I like to work with && because it cut out some lines.

2022-05-20 13:28 UTC, Puszkarek requested changes

2022-05-20 13:28 UTC, Puszkarek commented on docs-generator/readme/functions.md
> +## context
S: capitalize the titles

2022-05-20 13:28 UTC, Puszkarek commented on docs-generator/settings/licenses.ts
> + **************************************************************************/`;
W: you can get this format from `.config\license-header.json`
by the way, is necessary? we already have a command to run for add the license on files
`npm run format` will execute `npx license-check-and-add add -f ./.config/license-header.json`

2022-05-20 13:37 UTC, GeraldWicks commented on docs-generator/assets/style.css
> +		right: 0 !important;
This is from the default typedoc generator, so, to keep the things as standard it would be better not change what is inside assets folder.

2022-05-20 15:23 UTC, GeraldWicks commented on docs-generator/main.ts
> +createDocsPages(pages);
Didn't understand

2022-05-20 19:23 UTC, Puszkarek commented on docs-generator/files-manager/add-code-block.ts
> +		console.log(`Was not possible to add the code block, ${filePath} does note exists`);
M: use `console.error` instead

2022-05-20 19:23 UTC, Puszkarek commented on docs-generator/files-manager/copy-file.ts
> +		console.log(`Was not possible to add the code block, ${pathWhereFileIsCopied} does note exists`);
M: use `console.error` instead

2022-05-20 19:24 UTC, Puszkarek commented on docs-generator/files-manager/remove-file.ts
> +		console.log(`Was not possible to remove this file, ${filePath} does note exists`);
M: use `console.error` instead

2022-05-20 19:27 UTC, Puszkarek commented on docs-generator/get-all-pages.ts
> +		entryPoints: files.length > subFolders.length ? [folderPath] : getResolveEntryPoints(folderPath),
M: we can pass the result of `files.length > subFolders.length` to a const to be more clear

2022-05-26 14:14 UTC, merged